## Create a pod using the node selector and labels. We can do that for other objects also like replicaset, deployment etc.

---
kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: development
spec:
   containers:
      - name: c00
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo Hello This is a pod by selectors; sleep 5 ; done"]
   nodeSelector:
     hardware: t2-medium
